Repository carbon-app/carbon, pull requests merged in 2019-09, with the labels that each got.

#857 Spanish translation improved
  docs/README.es.md
Labels: merge when passing, translator

#858 Fix translation error
  docs/README.de.md
Labels: merge when passing, translator

#863 Validate on GitHub CI
  .github/workflows/validate.yml
  .travis.yml
Labels: merge when passing

#866 Old TODOs / PWA work
  components/Editor.js
  components/Meta.js
  lib/util.js
  next.config.js
  static/brand/apple-touch-icon.png
Labels: maintenance, merge when passing

#867 Move login button
  components/Editor.js
  components/EditorContainer.js
  components/LoginButton.js
Labels: merge when passing

#869 Remove use memo from settings
  components/Settings.js
Labels: maintenance, merge when passing

#871 Kbd elements in about
  components/ExportMenu.js
  components/style/Reset.js
  pages/about.js
Labels: merge when passing

#872 Use checkbox input for toggle
  components/Toggle.js
Labels: maintenance, merge when passing

#873 Improve background select
  components/BackgroundSelect.js
Labels: maintenance, merge when passing

#874 Upgrade Deps
  package.json
  yarn.lock
Labels: maintenance, merge when passing
