Repository carbon-app/carbon, pull requests merged in 2019-10, with the labels that each got.

#876 Add loading state to export button
  components/ExportMenu.js
Labels: merge when passing

#878 Load selected lines from query params
  .all-contributorsrc
  README.md
  components/Carbon.js
  docs/README.br.pt.md
  docs/README.cn.zh.md
  docs/README.de.md
  docs/README.es.md
  docs/README.fr.md
  docs/README.hi.md
  docs/README.ja.md
  docs/README.kr.md
  docs/README.ml.md
  docs/README.ta.md
  docs/README.tr.md
  lib/routing.js
  lib/util.js
Labels: Hacktoberfest, merge when passing

#886 Upgrade next and react
  package.json
  yarn.lock
Labels: merge when passing

#883 Optimize PNGs and SVGs
  static/brand/apple-touch-icon.png
  static/brand/banner.png
  static/brand/desktop.png
  static/brand/icon.png
  static/brand/logo-banner-transparent.png
  static/brand/logo-banner.png
  static/brand/logo-square.png
  static/brand/social-banner.png
  static/presets/0.png
  static/presets/1.png
  static/presets/2.png
  static/presets/3.png
  static/presets/4.png
  static/presets/5.png
  static/presets/6.png
  static/presets/7.png
  static/presets/8.png
  static/presets/9.png
  static/svg/github.svg
  static/svg/open-source-companies.svg
  static/svg/person.svg
  static/svg/snippets.svg
Labels: Hacktoberfest

#887 Add a11y-dark theme
  lib/constants.js
Labels: merge when passing, theme/language

#896 use constant colors
  components/Meta.js
  components/style/Reset.js
Labels: merge when passing

#879 Display whitespace
  components/Carbon.js
  components/Settings.js
  lib/constants.js
  package.json
  yarn.lock
Labels: Hacktoberfest

#898 RFC: restructure settings menu
  components/MenuButton.js
  components/Settings.js
Labels: Hacktoberfest

#902 Upgrade deps
  package.json
  yarn.lock
Labels: rebase when passing
