Repository carbon-app/carbon, pull requests merged in 2020-06, with the labels that each got.

#949 add 'width' option for Carbon container
  components/Carbon.js
  components/Editor.js
  components/Settings.js
  components/WidthHandler.js
  lib/constants.js
Labels: contributor, squash when passing

#1036 refactor(color-picker): drag the pointer smoothly
  components/ColorPicker.js
Labels: contributor, maintenance

#1041 Read container width and height at copy time
  components/CopyMenu.js
  components/Editor.js
Labels: squash when passing

#1040 Maintenance: remove constructors
  components/Editor.js
  components/ImagePicker.js
Labels: maintenance
