Repository carbon-app/carbon, pull requests merged in 2020-08, with the labels that each got.

#1076 Update all contribs
  README.md
  docs/README.br.pt.md
  docs/README.cn.zh.md
  docs/README.de.md
  docs/README.es.md
  docs/README.fr.md
  docs/README.hi.md
  docs/README.ja.md
  docs/README.kr.md
  docs/README.ml.md
  docs/README.pl.md
  docs/README.se.md
  docs/README.ta.md
  docs/README.tr.md
Labels: maintenance

#1077 Fix IBM Plex Mono font is missing in Safari
  components/style/Font.js
Labels: bugfix, contributor, squash when passing

#1080 Clean up Fonts.js
  components/style/Font.js
  cypress/integration/gist.spec.js
Labels: maintenance

#1084 Delete code that once included a transparent row for Twitter
  components/Carbon.js
  components/Editor.js
  pages/embed/index.js
Labels: maintenance

#1085 Attempt to fix integration tests
  cypress/integration/background-color.spec.js
Labels: squash when passing
