Repository carbon-app/carbon, pull requests merged in 2020-09, with the labels that each got.

#1097 Fix encoding % sign breaking SVG background
  lib/dom-to-image.js
Labels: bugfix

#1101 Clean up escapePercentSign
  lib/dom-to-image.js
Labels: maintenance, squash when passing

#1102 Move toasts to bottom right
  components/Toasts.js
Labels: bugfix, squash when passing
