Repository carbon-app/carbon, pull requests merged in 2021-03, with the labels that each got.

#1186 Fira Code Font - Set to latest version, switch CDN
  components/style/Font.js
Labels: maintenance

#1191 Remove mock stripe
  components/Billing.js
  package.json
  pages/account.js
  yarn.lock
Labels: maintenance

#1194 Update wren referral link
  cypress/integration/security.spec.js
  next.config.js
Labels: squash when passing

#1193 Added contributors page 🎉
  pages/about.js
Labels: contributor

#1192 Don't sanitize payload for storage
  lib/api.js
Labels: bugfix
